### ISSUE TITLE
fontsize bằng nhau

### ISSUE THREAD

**Issue by phinv90** [duongdam/item-checked-custom#3]
![Ảnh chụp Màn hình 2021-06-24 lúc 12 12 19](https://user-images.githubusercontent.com/45842801/123206195-7d512000-d4e5-11eb-894f-5405e32b1c38.png)

**Comment by duongdam** [comment]
Fixed in https://github.com/duongdam/item-checked-custom/commit/fdc2965a8bc525308c6f94da3206c5e912c7f49b
